T25025
endlessm/hack-toolbox-app pull request #125
Opened 2019-01-18 21:25 UTC by cfoch

https://phabricator.endlessm.com/T25025

2019-01-31 21:20 UTC, ptomato approved these changes
This code looks good, I will post some questions for David in the Phabricator task but if we decide not to make any changes as a result of the questions, then we can merge this.

2019-02-04 22:34 UTC, ptomato requested changes
One small change requested. I think it's closer to what David was describing, if we only vary the backspace/delete key sound that is played during a normal backspace/delete key press, not when there is a selection. (Because when you stop typing and select a region with the mouse as I expect most players will, then you exceed the pitch reset delay anyway.)

Otherwise looking and working well.

2019-02-04 22:34 UTC, ptomato commented on src/codeview.js
> +        const options = this._calculateKeystrokePitch();
I would move this inside the `if (deletedLength === 1)` condition, so that we are only affecting the normal use of the backspace or delete keys, with no selection.

2019-02-04 22:34 UTC, ptomato commented on src/codeview.js
> +            sound.playFull('codeview/keypress/delete-selection', options);
...and change this line back to what it was.

2019-02-05 04:06 UTC, cfoch commented
I agree with the comments. I was thinking the same but not sure if you would be thinking the same, too.

2019-02-05 17:33 UTC, ptomato approved these changes
:+1:

2019-02-05 17:35 UTC, merged