Reset and minimize button
endlessm/hack-toolbox-app pull request #14
Opened 2018-10-04 22:10 UTC by ptomato

https://phabricator.endlessm.com/T23957

2018-10-04 23:38 UTC, cosimoc requested changes

2018-10-04 23:38 UTC, cosimoc commented on src/framework/toolbox.js
> +        props.title = 'Hack Modules';
Should be marked for translation.

2018-10-04 23:38 UTC, cosimoc commented on src/toolbox.js
> +            'Hack'),
Should also be marked for translation.

2018-10-04 23:38 UTC, cosimoc commented on src/toolbox.js
> +            label: 'Reset All',
Should also be marked for translation

2018-10-04 23:38 UTC, cosimoc commented on src/toolbox.js
> +        });
Could be a bit cleaner to create this before chaining up, so you can remove the `if (this._headerbar)` check in the setter below?

2018-10-05 17:54 UTC, ptomato commented
Fixed.

2018-10-05 18:01 UTC, merged