Hackdex 2: Implement new hover spec
endlessm/hack-toolbox-app pull request #202
Opened 2019-05-06 16:18 UTC by xrgranados

https://phabricator.endlessm.com/T26460

2019-05-06 21:34 UTC, cosimoc commented
@xrgranados I haven't looked at the code, but could you please fix the `eslint` failures above?

2019-05-06 23:38 UTC, ptomato requested changes
Once the hackdex PR is updated, please sync the changes to this repo again. Otherwise, it looks good after fixing the CI failure.

2019-05-06 23:43 UTC, xrgranados commented
`eslint` fixes applied.
Please review and confirm.

2019-05-08 19:15 UTC, ptomato approved these changes

2019-05-08 19:15 UTC, merged