Sidetrack & LightSpeed: Scope notify signal per model for code update
endlessm/hack-toolbox-app pull request #211
Opened 2019-05-15 19:20 UTC by MegFord

https://phabricator.endlessm.com/T26141

2019-05-15 19:46 UTC, MegFord commented
@ptomato one thing I'm a little worried about is that adding/blocking/removing so many signals in LightSpeed will slow things down. Can you let me know if you see any slowdown, and if so, if you can recommend a better way to re-write the notify signals in that app?

2019-05-15 22:20 UTC, ptomato requested changes
OK, it took me a while and a lot of poking around to understand this, but I now see why the changes to the variables codeviews are necessary as well as fixing the user functions codeviews. That was the part I didn't understand the other day when we talked on Slack about this. Thanks for the thorough investigation, I found this bug really difficult to wrap my head around.

2019-05-15 22:20 UTC, ptomato commented on src/LightSpeed/controlpanel.js
> +        this._notifyHandler = {};
I think it would be better to use `new Map()` here instead of `{}`, since you will get a more idiomatic way to tell if the map is empty than "length of keys is 0 and constructor is Object", as well as setting/deleting keys.

2019-05-15 22:20 UTC, ptomato commented on src/LightSpeed/controlpanel.js
> +                this._disconnectNotify();
I'm not sure, but this condition seems backwards on first reading? It seems like disconnectNotify should be called only if notifyHandler is not empty. The code works, though, so maybe I'm just not understanding it. A comment might be useful in that case :smile:

2019-05-15 22:20 UTC, ptomato commented on src/LightSpeed/controlpanel.js
> +        this.bindingInfo = {
It's unlikely, but just to be sure I'd move this initializer into the constructor, in case any of the other methods that use this were called before this method.

Alternatively, it could end up being easier to iterate through `this._notifyHandler` in those other methods, instead of through `this.bindingInfo`, since you only need the keys. If you take the suggestion above about using a map, `Map` has a `forEach()` method which you could use.

2019-05-15 22:20 UTC, ptomato commented on src/LightSpeed/controlpanel.js
> +        this.set_property('needs-attention', false);
Is this related to the fix or just a general improvement? If the latter, split it out into a separate commit.

2019-05-15 22:20 UTC, ptomato commented on src/RileyMaze/RMZUnit.js
> +        this.robotANotify = this._model.connect('notify::robotADirection', () => {
Prefix these property names with an underscore to indicate they are private. Optionally, you could use a notifyHandlers map like in Lightspeed to be more future-proof.

2019-05-15 22:22 UTC, ptomato commented
PS. I didn't notice a slowdown, but I also didn't test it on the Hack laptop.

If it slows down, one way to solve it differently could be to continue connecting to the full `notify` signal in the variables codeviews, and just check the property name at the start of the signal handler, and return early if it's not a property we're interested in. I'd still use the `notify::propName` in the user functions codeviews though, since that really is only one property.

2019-05-16 16:08 UTC, MegFord commented on src/LightSpeed/controlpanel.js
> +                this._disconnectNotify();
Ha, yeah, I forgot to ! this check :/

2019-05-16 21:16 UTC, MegFord commented on src/LightSpeed/controlpanel.js
> +        this.set_property('needs-attention', false);
I'm actually seeing the issue this fixed in a few places. I'l break it out into another bug.

2019-05-16 21:40 UTC, MegFord commented on src/LightSpeed/controlpanel.js
> +        this.set_property('needs-attention', false);
So I see that I also fixed this in RMZUnits in the PR so I'll leave it in if that's okay. This line fixes a regression caused by using the specific notify signals. In the past the generic notify was being called and that called reset() which changed this property to false when the level advanced.

2019-05-16 23:12 UTC, ptomato approved these changes
Works fine, go ahead and merge it after making the change, if you agree with it.

2019-05-16 23:12 UTC, ptomato commented on src/LightSpeed/controlpanel.js
> +        const props = {
A more idiomatic way to do this would be
```js
const props = ['scoreTarget', 'astronautSize', 'shipAsset', 'shipSize', 'shipSpeed'];
if (props.includes(pspec.name))
    this.reset();
```

2019-05-16 23:12 UTC, ptomato commented on src/RileyMaze/RMZUnit.js
> +        const props = {
Ditto here.

2019-05-17 14:04 UTC, MegFord commented on src/LightSpeed/controlpanel.js
> +        const props = {
Oh, nice, I didn't realize JS had a way to do check in array that wasn't O(n)

2019-05-17 14:29 UTC, merged

2019-05-17 17:13 UTC, ptomato commented on src/LightSpeed/controlpanel.js
> +        const props = {
Oh, good point, I assume this is still O(n)... but with 5 entries I wouldn't be too concerned about it.

If O(1) is really necessary I'd suggest using a Set:
```js
const props = new Set(['scoreTarget', blah, blah...]);
if (props.has(pspec.name)) ...
```

2019-05-17 17:23 UTC, MegFord commented on src/LightSpeed/controlpanel.js
> +        const props = {
Yeah in this case it makes no difference. I just got used to using O(1) operations when I was doing operations on large data sets, so it was force of habit. Thanks for the info!