Sidetrack: Add Robot Images to Show Up/Down State
endlessm/hack-toolbox-app pull request #217
Opened 2019-05-17 18:31 UTC by MegFord

https://phabricator.endlessm.com/T26660

2019-05-17 18:43 UTC, eos-shell-build commented
Build finished.

2019-05-17 19:19 UTC, ptomato requested changes
This seems to work correctly, but the flipped robot assets don't match the assets in Sidetrack. So these assets might not be the latest ones?

![Screenshot from 2019-05-17 12-10-26](https://user-images.githubusercontent.com/459371/57950686-d37e1e80-789c-11e9-8f89-95a6305ef051.png)

(This is with both robots flipped. note the red forehead lights are visible on the robots in the game, but not in the toolbox asset, and the blue forehead lights are visible on the toolbox asset, but not in the game.)

2019-05-20 14:51 UTC, MegFord commented
Here's a screenshot with the new images from Anita ![robots](https://user-images.githubusercontent.com/835693/58030800-d4a18c80-7ae4-11e9-99f8-bd92fda6f52a.png)

2019-05-20 14:58 UTC, eos-shell-build commented
Build finished.

2019-05-20 18:37 UTC, ptomato approved these changes
Assets looking good now, thanks!

2019-05-20 18:37 UTC, merged